name: Keep Streamlit Alive

on:
  schedule:
    - cron: "0 * * * *" # Berjalan setiap jam
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to Streamlit App
        run: |
          curl -I https://newspage.streamlit.app
